/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "lora.pb-c.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void lo_ra_frame_init(
    struct lo_ra_frame_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->tanwa_battery.is_present = false;
    self_p->tanwa_state.is_present = false;
    self_p->tanwa_flags.is_present = false;
    self_p->tanwa_thrust.is_present = false;
    self_p->tanwa_tank_weight.is_present = false;
    self_p->tanwa_temp_post_n2o_fill.is_present = false;
    self_p->tanwa_temp_filling_wall.is_present = false;
    self_p->tanwa_post_fill_n2o_pres.is_present = false;
    self_p->tanwa_cutoff_n2o_pres.is_present = false;
    self_p->tanwa_droid_n2o_pres.is_present = false;
    self_p->tanwa_pre_reg_n2_pres.is_present = false;
    self_p->tanwa_post_reg_n2_pres.is_present = false;
    self_p->tanwa_post_fill_n2_pres.is_present = false;
    self_p->tanwa_droid_n2_pres.is_present = false;
    self_p->tanwa_comb_chamber_pres.is_present = false;
}

void lo_ra_frame_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct lo_ra_frame_t *self_p)
{
    if (self_p->tanwa_comb_chamber_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 15, self_p->tanwa_comb_chamber_pres.value);
    }
    if (self_p->tanwa_droid_n2_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 14, self_p->tanwa_droid_n2_pres.value);
    }
    if (self_p->tanwa_post_fill_n2_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 13, self_p->tanwa_post_fill_n2_pres.value);
    }
    if (self_p->tanwa_post_reg_n2_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 12, self_p->tanwa_post_reg_n2_pres.value);
    }
    if (self_p->tanwa_pre_reg_n2_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 11, self_p->tanwa_pre_reg_n2_pres.value);
    }
    if (self_p->tanwa_droid_n2o_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 10, self_p->tanwa_droid_n2o_pres.value);
    }
    if (self_p->tanwa_cutoff_n2o_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 9, self_p->tanwa_cutoff_n2o_pres.value);
    }
    if (self_p->tanwa_post_fill_n2o_pres.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 8, self_p->tanwa_post_fill_n2o_pres.value);
    }
    if (self_p->tanwa_temp_filling_wall.is_present) {
        pbtools_encoder_write_sint32_always(encoder_p, 7, self_p->tanwa_temp_filling_wall.value);
    }
    if (self_p->tanwa_temp_post_n2o_fill.is_present) {
        pbtools_encoder_write_sint32_always(encoder_p, 6, self_p->tanwa_temp_post_n2o_fill.value);
    }
    if (self_p->tanwa_tank_weight.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 5, self_p->tanwa_tank_weight.value);
    }
    if (self_p->tanwa_thrust.is_present) {
        pbtools_encoder_write_sint32_always(encoder_p, 4, self_p->tanwa_thrust.value);
    }
    if (self_p->tanwa_flags.is_present) {
        pbtools_encoder_write_fixed32_always(encoder_p, 3, self_p->tanwa_flags.value);
    }
    if (self_p->tanwa_state.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 2, self_p->tanwa_state.value);
    }
    if (self_p->tanwa_battery.is_present) {
        pbtools_encoder_write_fixed32_always(encoder_p, 1, self_p->tanwa_battery.value);
    }
}

void lo_ra_frame_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct lo_ra_frame_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->tanwa_battery.is_present = true;
            self_p->tanwa_battery.value = pbtools_decoder_read_fixed32(decoder_p, wire_type);
            break;

        case 2:
            self_p->tanwa_state.is_present = true;
            self_p->tanwa_state.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->tanwa_flags.is_present = true;
            self_p->tanwa_flags.value = pbtools_decoder_read_fixed32(decoder_p, wire_type);
            break;

        case 4:
            self_p->tanwa_thrust.is_present = true;
            self_p->tanwa_thrust.value = pbtools_decoder_read_sint32(decoder_p, wire_type);
            break;

        case 5:
            self_p->tanwa_tank_weight.is_present = true;
            self_p->tanwa_tank_weight.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 6:
            self_p->tanwa_temp_post_n2o_fill.is_present = true;
            self_p->tanwa_temp_post_n2o_fill.value = pbtools_decoder_read_sint32(decoder_p, wire_type);
            break;

        case 7:
            self_p->tanwa_temp_filling_wall.is_present = true;
            self_p->tanwa_temp_filling_wall.value = pbtools_decoder_read_sint32(decoder_p, wire_type);
            break;

        case 8:
            self_p->tanwa_post_fill_n2o_pres.is_present = true;
            self_p->tanwa_post_fill_n2o_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 9:
            self_p->tanwa_cutoff_n2o_pres.is_present = true;
            self_p->tanwa_cutoff_n2o_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 10:
            self_p->tanwa_droid_n2o_pres.is_present = true;
            self_p->tanwa_droid_n2o_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 11:
            self_p->tanwa_pre_reg_n2_pres.is_present = true;
            self_p->tanwa_pre_reg_n2_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 12:
            self_p->tanwa_post_reg_n2_pres.is_present = true;
            self_p->tanwa_post_reg_n2_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 13:
            self_p->tanwa_post_fill_n2_pres.is_present = true;
            self_p->tanwa_post_fill_n2_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 14:
            self_p->tanwa_droid_n2_pres.is_present = true;
            self_p->tanwa_droid_n2_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 15:
            self_p->tanwa_comb_chamber_pres.is_present = true;
            self_p->tanwa_comb_chamber_pres.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void lo_ra_frame_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct lo_ra_frame_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct lo_ra_frame_t),
        (pbtools_message_encode_inner_t)lo_ra_frame_encode_inner);
}

void lo_ra_frame_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct lo_ra_frame_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct lo_ra_frame_t),
        (pbtools_message_init_t)lo_ra_frame_init,
        (pbtools_message_decode_inner_t)lo_ra_frame_decode_inner);
}

struct lo_ra_frame_t *
lo_ra_frame_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct lo_ra_frame_t),
                (pbtools_message_init_t)lo_ra_frame_init));
}

int lo_ra_frame_encode(
    struct lo_ra_frame_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)lo_ra_frame_encode_inner));
}

int lo_ra_frame_decode(
    struct lo_ra_frame_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)lo_ra_frame_decode_inner));
}

void lo_ra_command_init(
    struct lo_ra_command_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->lora_dev_id.is_present = false;
    self_p->sys_dev_id.is_present = false;
    self_p->command.is_present = false;
    self_p->payload.is_present = false;
}

void lo_ra_command_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct lo_ra_command_t *self_p)
{
    if (self_p->payload.is_present) {
        pbtools_encoder_write_int32_always(encoder_p, 4, self_p->payload.value);
    }
    if (self_p->command.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 3, self_p->command.value);
    }
    if (self_p->sys_dev_id.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 2, self_p->sys_dev_id.value);
    }
    if (self_p->lora_dev_id.is_present) {
        pbtools_encoder_write_uint32_always(encoder_p, 1, self_p->lora_dev_id.value);
    }
}

void lo_ra_command_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct lo_ra_command_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->lora_dev_id.is_present = true;
            self_p->lora_dev_id.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 2:
            self_p->sys_dev_id.is_present = true;
            self_p->sys_dev_id.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 3:
            self_p->command.is_present = true;
            self_p->command.value = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->payload.is_present = true;
            self_p->payload.value = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void lo_ra_command_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct lo_ra_command_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct lo_ra_command_t),
        (pbtools_message_encode_inner_t)lo_ra_command_encode_inner);
}

void lo_ra_command_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct lo_ra_command_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct lo_ra_command_t),
        (pbtools_message_init_t)lo_ra_command_init,
        (pbtools_message_decode_inner_t)lo_ra_command_decode_inner);
}

struct lo_ra_command_t *
lo_ra_command_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct lo_ra_command_t),
                (pbtools_message_init_t)lo_ra_command_init));
}

int lo_ra_command_encode(
    struct lo_ra_command_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)lo_ra_command_encode_inner));
}

int lo_ra_command_decode(
    struct lo_ra_command_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)lo_ra_command_decode_inner));
}
