/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef LORA_H
#define LORA_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"

/**
 * Message LoRaFrame.
 */
struct lo_ra_frame_repeated_t {
    int length;
    struct lo_ra_frame_t *items_p;
};

struct lo_ra_frame_t {
    struct pbtools_message_base_t base;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_battery;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_state;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_flags;
    struct {
        bool is_present;
        int32_t value;
    } tanwa_thrust;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_tank_weight;
    struct {
        bool is_present;
        int32_t value;
    } tanwa_temp_post_n2o_fill;
    struct {
        bool is_present;
        int32_t value;
    } tanwa_temp_filling_wall;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_post_fill_n2o_pres;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_cutoff_n2o_pres;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_droid_n2o_pres;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_pre_reg_n2_pres;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_post_reg_n2_pres;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_post_fill_n2_pres;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_droid_n2_pres;
    struct {
        bool is_present;
        uint32_t value;
    } tanwa_comb_chamber_pres;
};

/**
 * Message LoRaCommand.
 */
struct lo_ra_command_repeated_t {
    int length;
    struct lo_ra_command_t *items_p;
};

struct lo_ra_command_t {
    struct pbtools_message_base_t base;
    struct {
        bool is_present;
        uint32_t value;
    } lora_dev_id;
    struct {
        bool is_present;
        uint32_t value;
    } sys_dev_id;
    struct {
        bool is_present;
        uint32_t value;
    } command;
    struct {
        bool is_present;
        int32_t value;
    } payload;
};

/**
 * Encoding and decoding of LoRaFrame.
 */
struct lo_ra_frame_t *
lo_ra_frame_new(
    void *workspace_p,
    size_t size);

int lo_ra_frame_encode(
    struct lo_ra_frame_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int lo_ra_frame_decode(
    struct lo_ra_frame_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of LoRaCommand.
 */
struct lo_ra_command_t *
lo_ra_command_new(
    void *workspace_p,
    size_t size);

int lo_ra_command_encode(
    struct lo_ra_command_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int lo_ra_command_decode(
    struct lo_ra_command_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void lo_ra_frame_init(
    struct lo_ra_frame_t *self_p,
    struct pbtools_heap_t *heap_p);

void lo_ra_frame_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct lo_ra_frame_t *self_p);

void lo_ra_frame_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct lo_ra_frame_t *self_p);

void lo_ra_frame_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct lo_ra_frame_repeated_t *repeated_p);

void lo_ra_frame_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct lo_ra_frame_repeated_t *repeated_p);

void lo_ra_command_init(
    struct lo_ra_command_t *self_p,
    struct pbtools_heap_t *heap_p);

void lo_ra_command_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct lo_ra_command_t *self_p);

void lo_ra_command_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct lo_ra_command_t *self_p);

void lo_ra_command_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct lo_ra_command_repeated_t *repeated_p);

void lo_ra_command_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct lo_ra_command_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
