syntax = "proto3";
package obc;

message MCBFrame {
    // === MCB ===
    optional uint32 mcb_state = 1;
    optional uint32 uptime_ms = 2;
    optional sint32 flight_time_ms = 3;
    optional uint32 mcb_batt = 4;
    optional float gps_lat = 5;
    optional float gps_long = 6;
    optional bool gps_sat_ok = 7;
    optional sint32 altitude_m = 8;
    optional sint32 velocity_m_s = 9;
    optional sint32 mcb_temperature = 10;
    optional float euler_fi = 11;
    optional float euler_psi = 12;
    optional float euler_theta = 13;

    // === Recovery bitfield ===
    // bit0: separation_switch_1
    // bit1: separation_switch_2
    // bit2: stage1_done
    // bit3: stage2_done
    // bit4: telemetrum_1_stage
    // bit5: telemetrum_2_stage
    // bit6: easy_mini_1_stage
    // bit7: easy_mini_2_stage
    // bit8: is_tele_active
    // bit9: is_easy_mini_active
    optional fixed32 recovery_flags = 14;

    // === Pitot ===
    optional uint32 pitot_battery = 15;
    optional sint32 pitot_altitude = 16;
    optional sint32 pitot_velocity = 17;
    optional sint32 pitot_temperature = 18;

    // === Main/Vent bitfield ===
    // bit0: OX_MAIN_STATE
    // bit1: N2_MAIN_STATE
    // bit2: OX_VENT_STATE
    // bit3: ETH_MAIN_STATE
    // bit4: ETH_VENT_STATE
    // bit5: N2_VENT_STATE
    optional fixed32 main_vent_flags = 19;

    optional fixed32 n2_vent_bit_data_a = 20;

    optional fixed32 ox_vent_eth_main_bit_data_a = 21;
    optional fixed32 ox_vent_eth_main_bit_data_b = 22;
    optional fixed32 ox_vent_eth_main_bit_data_c = 23;

    optional fixed32 ox_main_bit_data_a = 24;
    optional fixed32 ox_main_bit_data_b = 25;

    optional fixed32 eth_vent_n2_main_bit_data_a = 26;
    optional fixed32 eth_vent_n2_main_bit_data_b = 27;

    optional uint32 auto_vent_setting = 28;

    // === Payload ===
    optional uint32 payload_battery = 29;

    // === ESP-NOW connection bitfield ===
    // bit0: payload_connected
    // bit1: tanwa_connected
    // bit2: eth_vent_valve_connected
    // bit3: ox_main_connected
    // bit4: ox_vent_eth_main_connected
    // bit5: n2_vent_connected
    // bit6: pitot_connected
    optional fixed32 esp_now_connected_flags = 30;

    // === ESP-NOW wake-up bitfield ===
    // bit0: payload_wkup
    // bit1: eth_vent_valve_wkup
    // bit2: ox_main_wkup
    // bit3: ox_vent_eth_main_wkup
    // bit4: n2_vent_wkup
    // bit5: pitot_wkup
    optional fixed32 esp_now_wkup_flags = 31;

    optional fixed32 errors = 32;
}

message TanwaFrame {
    // === Tanwa ===
    optional fixed32 tanwa_battery = 1;
    optional uint32 tanwa_state = 2;

    // 8 bytes

    // === Tanwa CAN connections & status ===
    // bit0: CAN_Weights_connection
    // bit1: CAN_Utility_connection
    // bit2: CAN_Sensor_connection
    // bit3: CAN_Power_connection
    // bit4: CAN_Solenoid_connection
    // bit5: igniter_1_continuity
    // bit6: igniter_2_continuity
    // bit7: soft_arm
    // bit8: abort_button
    // bit9: fill_N2O_state
    // bit10: depr_N2O_state
    // bit11: fill_N2_state
    // bit12: depr_N2_state
    // bit13: droid_N2O_state
    // bit14: droid_N2_state
    // bit15: heating_tank_state
    // bit16: heating_valves_state
    optional fixed32 tanwa_flags = 3;

    optional sint32 tanwa_thrust = 4;
    optional uint32 tanwa_tank_weight = 5;
    optional sint32 tanwa_temp_post_n2o_fill = 6;
    optional sint32 tanwa_temp_filling_wall = 7;

    // Tanwa pressures
    optional uint32 tanwa_post_fill_n2o_pres = 8;
    optional uint32 tanwa_cutoff_n2o_pres = 9;
    optional uint32 tanwa_droid_n2o_pres = 10;
    optional uint32 tanwa_pre_reg_n2_pres = 11;
    optional uint32 tanwa_post_reg_n2_pres = 12;
    optional uint32 tanwa_post_fill_n2_pres = 13;
    optional uint32 tanwa_droid_n2_pres = 14;
    optional uint32 tanwa_comb_chamber_pres = 15;
}

message AppFrame {
    optional uint32 lora_dev_id = 1;
    optional uint32 sys_dev_id = 2;
    optional uint32 command = 3;
    optional int32 payload = 4;
}

message LoRaFrame {
    oneof frame {
        MCBFrame mcb_frame = 1;
        TanwaFrame tanwa_frame = 2;
        AppFrame app_frame = 3;
    }
}